
import { Product, Category } from '../types';
import { v4 as uuidv4 } from 'uuid';

export const categories: { id: string; name: Category; icon: string }[] = [
  { id: uuidv4(), name: 'all', icon: '🛒' },
  { id: uuidv4(), name: 'fruits', icon: '🍎' },
  { id: uuidv4(), name: 'vegetables', icon: '🥦' },
  { id: uuidv4(), name: 'dairy', icon: '🥛' },
  { id: uuidv4(), name: 'bakery', icon: '🍞' },
  { id: uuidv4(), name: 'meat', icon: '🥩' },
  { id: uuidv4(), name: 'beverages', icon: '🧃' },
  { id: uuidv4(), name: 'snacks', icon: '🍪' },
];

export const products: Product[] = [
  {
    id: uuidv4(),
    name: "Organic Apples",
    description: "Fresh, crisp organic apples. Locally sourced and perfect for healthy snacking or baking.",
    price: 3.99,
    imageUrl: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "fruits",
    stock: 50,
    rating: 4.8,
    unit: "lb",
  },
  {
    id: uuidv4(),
    name: "Fresh Bananas",
    description: "Perfectly ripened bananas, rich in potassium and natural sweetness.",
    price: 1.99,
    imageUrl: "https://images.unsplash.com/photo-1481349518771-20055b2a7b24?q=80&w=2139&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "fruits",
    stock: 40,
    rating: 4.5,
    unit: "bunch",
    discountPercentage: 10,
  },
  {
    id: uuidv4(),
    name: "Broccoli",
    description: "Farm-fresh broccoli, loaded with vitamins and minerals.",
    price: 2.49,
    imageUrl: "https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "vegetables",
    stock: 30,
    rating: 4.3,
    unit: "head",
  },
  {
    id: uuidv4(),
    name: "Carrot Bundle",
    description: "Sweet and crunchy carrots, perfect for salads, cooking, or snacking.",
    price: 2.29,
    imageUrl: "https://images.unsplash.com/photo-1447175008436-054170c2e979?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "vegetables",
    stock: 35,
    rating: 4.6,
    unit: "bundle",
  },
  {
    id: uuidv4(),
    name: "Organic Whole Milk",
    description: "Creamy organic whole milk from grass-fed cows. No hormones or antibiotics.",
    price: 3.99,
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "dairy",
    stock: 25,
    rating: 4.7,
    unit: "half gallon",
  },
  {
    id: uuidv4(),
    name: "Greek Yogurt",
    description: "Thick, creamy Greek yogurt. High in protein and perfect for breakfast or snacking.",
    price: 4.99,
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "dairy",
    stock: 20,
    rating: 4.8,
    unit: "32oz tub",
    discountPercentage: 15,
  },
  {
    id: uuidv4(),
    name: "Artisan Sourdough Bread",
    description: "Freshly baked artisan sourdough bread with a perfect crust and chewy interior.",
    price: 5.99,
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "bakery",
    stock: 15,
    rating: 4.9,
    unit: "loaf",
  },
  {
    id: uuidv4(),
    name: "Chocolate Croissants",
    description: "Buttery, flaky croissants with rich chocolate filling. Baked fresh daily.",
    price: 3.49,
    imageUrl: "https://images.unsplash.com/photo-1623334044303-241021148842?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "bakery",
    stock: 18,
    rating: 4.7,
    unit: "each",
  },
  {
    id: uuidv4(),
    name: "Grass-fed Ground Beef",
    description: "Premium grass-fed ground beef. Lean and flavorful, perfect for burgers or meatballs.",
    price: 8.99,
    imageUrl: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "meat",
    stock: 20,
    rating: 4.6,
    unit: "lb",
  },
  {
    id: uuidv4(),
    name: "Organic Chicken Breast",
    description: "Boneless, skinless organic chicken breasts. Free-range and hormone-free.",
    price: 9.99,
    imageUrl: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "meat",
    stock: 15,
    rating: 4.8,
    unit: "lb",
    discountPercentage: 5,
  },
  {
    id: uuidv4(),
    name: "Organic Orange Juice",
    description: "Freshly squeezed organic orange juice. No added sugars or preservatives.",
    price: 5.99,
    imageUrl: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "beverages",
    stock: 25,
    rating: 4.7,
    unit: "half gallon",
  },
  {
    id: uuidv4(),
    name: "Sparkling Water Variety Pack",
    description: "Refreshing sparkling water in assorted flavors. Zero calories and no artificial sweeteners.",
    price: 12.99,
    imageUrl: "https://images.unsplash.com/photo-1598214886806-c87b84b7078b?q=80&w=1925&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "beverages",
    stock: 30,
    rating: 4.5,
    unit: "12-pack",
  },
  {
    id: uuidv4(),
    name: "Tortilla Chips",
    description: "Crispy, restaurant-style tortilla chips made with organic corn.",
    price: 3.99,
    imageUrl: "https://images.unsplash.com/photo-1613919113640-25732ec5e61f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "snacks",
    stock: 40,
    rating: 4.4,
    unit: "12oz bag",
  },
  {
    id: uuidv4(),
    name: "Mixed Nuts",
    description: "Premium blend of roasted almonds, cashews, walnuts, and pecans. Lightly salted.",
    price: 7.99,
    imageUrl: "https://images.unsplash.com/photo-1525053910098-e44f5a898d4d?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "snacks",
    stock: 25,
    rating: 4.6,
    unit: "8oz bag",
    discountPercentage: 8,
  },
  {
    id: uuidv4(),
    name: "Organic Strawberries",
    description: "Sweet, juicy organic strawberries. Perfect for snacking or desserts.",
    price: 4.99,
    imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "fruits",
    stock: 30,
    rating: 4.7,
    unit: "16oz package",
  },
  {
    id: uuidv4(),
    name: "Fresh Spinach",
    description: "Tender, organic baby spinach leaves. Rich in iron and vitamins.",
    price: 3.49,
    imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "vegetables",
    stock: 25,
    rating: 4.5,
    unit: "8oz bag",
  },
];
